# Generated by Django 5.1.4 on 2024-12-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faFirstName', models.CharField(max_length=150)),
                ('faLastName', models.CharField(max_length=150)),
                ('enFirstName', models.CharField(max_length=200)),
                ('enLastName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('faFatherName', models.CharField(max_length=100)),
                ('birthDay', models.DateField()),
                ('nationalCode', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('cardNumber', models.CharField(max_length=16)),
                ('shabaNumber', models.CharField(max_length=24)),
                ('faTerminalName', models.CharField(max_length=100)),
                ('enTerminalName', models.CharField(max_length=120)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
